FROM golang:1.22-alpine AS builder

WORKDIR /build

COPY app/worker/go.mod app/worker/go.sum ./
RUN go mod download

COPY app/worker/ ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o worker main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /build/worker /app/worker

CMD ["/app/worker"]