FROM golang:1.23-alpine AS builder

WORKDIR /build

COPY app/api/go.mod app/api/go.sum ./
RUN go mod download

COPY app/api/ ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /build/api /app/api

EXPOSE 8080

CMD ["/app/api"]