name: project-3-destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TERRAFORM_WORKING_DIRECTORY: project-3-data-pipeline/terraform/environments/dev

concurrency:
  group: project-3-destroy
  cancel-in-progress: false

jobs:
  terraform-destroy:
    name: Destroy infrastructure
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'project-3-dev' }}

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      TF_VAR_alert_email: ${{ vars.ALERT_EMAIL }}

    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-project-3-destroy

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="alert_email=${{ vars.PROJECT3_ALERT_EMAIL }}"
